export default {
  FINANCIAL_OVERVIEW: 'EXPRESS_FINANCIAL_OVERVIEW',
  BRANCH_REPUTATION: 'EXPRESS_BRANCH_REPUTATION',
  CUSTOMERS: 'EXPRESS_CUSTOMERS',
  SPENDING_BY_CATEGORY: 'EXPRESS_SPENDING_BY_CATEGORY',
  ORDER_BY_PAYMENT_TYPE: 'EXPRESS_ORDER_BY_PAYMENT_TYPE',
  CUSTOMER_STATISTICS: 'CUSTOMER_STATISTICS',
  PROFIT_CHART: 'PROFIT_CHART',
  SPENDINGS_PAGE: 'SPENDINGS_PAGE',
  EMPTY: 'EXPRESS_EMPTY',
};
