// UPC = Users Profile Customer
export const ORDERS = "ORDERS";
export const BRANCH_ORDERS = "BRANCH_ORDERS";
export const PICKUPS = "PICKUPS";
export const DELIVERIES = "DELIVERIES";
export const SHIPMENTS = "SHIPMENTS";
export const SHIPMENTS_BOXES = "SHIPMENTS_BOXES";
export const FEDEX = "FEDEX";
export const WAREHOUSE = "WAREHOUSE";
export const SPENDINGS = "SPENDINGS";
export const SHIPMENT_SINGLE_VIEW = "SHIPMENT_SINGLE_VIEW";
export const UPC_ORDERS = "UPC_ORDERS";
export const UPC_FEDEX = "UPC_FEDEX";
export const UPC_ONLINE_ORDERS = "UPC_ONLINE_ORDERS";
export const TRACKING_ORDERS = "TRACKING_ORDERS";
