export default {
  APPLICATION_USER_INFO: 'EXPRESS_APPLICATION_USER_INFO',
  APPLICATION_SHOW_MODAL: 'EXPRESS_APPLICATION_SHOW_MODAL',
  APPLICATION_HIDE_MODAL: 'EXPRESS_APPLICATION_HIDE_MODAL',
  APPLICATION_SHOW_ALERT: 'EXPRESS_APPLICATION_SHOW_ALERT',
  APPLICATION_HIDE_ALERT: 'EXPRESS_APPLICATION_HIDE_ALERT',
  APPLICATION_SHOW_FULLSCREEN_MODAL: 'EXPRESS_APPLICATION_SHOW_FULLSCREEN_MODAL',
  APPLICATION_PUSH_STACK_FULLSCREEN_MODAL: 'EXPRESS_APPLICATION_PUSH_STACK_FULLSCREEN_MODAL',
  APPLICATION_POP_STACK_FULLSCREEN_MODAL: 'EXPRESS_APPLICATION_POP_STACK_FULLSCREEN_MODAL',
  APPLICATION_HIDE_FULLSCREEN_MODAL: 'EXPRESS_APPLICATION_HIDE_FULLSCREEN_MODAL'
};
