export default {
  CREATE_ADD_BOX: 'CREATE_ADD_BOX',
  BOX_CREATE_IMAGE: 'BOX_CREATE_IMAGE',
  BOX_CLEAR_IMAGE: 'BOX_CLEAR_IMAGE',
  BOX_DELETE_IMAGE: 'BOX_DELETE_IMAGE',
  BOX_CLEAR_STATE: 'BOX_CLEAR_STATE',
  UPDATE_BOX: 'UPDATE_BOX',
  DELETE_BOX: 'DELETE_BOX',
  BOX_SET_DATA: 'BOX_SET_DATA',
  BOX_SET_FREETIME: 'BOX_SET_FREETIME',
  BOX_SET_FREETIME_OPTIONS: 'BOX_SET_FREETIME_OPTIONS',
};
