export default {
  NOTIFICATION_CREATE_ITEM: 'EXPRESS_NOTIFICATION_CREATE_ITEM',
  NOTIFICATION_REMOVE_ITEM: 'EXPRESS_NOTIFICATION_REMOVE_ITEM',
  NOTIFICATION_REMOVE_LAST_ITEM: 'EXPRESS_NOTIFICATION_REMOVE_LAST_ITEM'
};
