export default {
  NAVBER_SET_TITLE: 'EXPRESS_NAVBER_SET_TITLE',
  NAVBER_SET_BREADCRUMB_TITLE: 'EXPRESS_NAVBER_SET_BREADCRUMB_TITLE',
  NAVBER_SET_BREADCRUMB_PATH: 'EXPRESS_NAVBER_SET_BREADCRUMB_PATH',
  CREATE_EVENT: 'CREATE_EVENT',
  GET_EVENTS: 'GET_EVENTS',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  GET_EVENT: 'GET_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT'
};
