export default {
  PICKUP_CREATE_FORM: 'PICKUP_CREATE_FORM',
  PICKUP_CREATE_CLEAR_STATE: 'PICKUP_CREATE_CLEAR_STATE',
  PICKUP_CREATE_ADD_FROM_DATE: 'PICKUP_CREATE_ADD_FROM_DATE',
  PICKUP_CREATE_ADD_TO_DATE: 'PICKUP_CREATE_ADD_TO_DATE',
  TABLE_PICKUP_SET_STATUSES: 'TABLE_PICKUP_SET_STATUSES',
  TABLE_PICKUP_FETCH_STATUSES: 'TABLE_PICKUP_FETCH_STATUSES',
  PICKUP_CREATE_UPDATE_BOX: 'PICKUP_CREATE_UPDATE_BOX',
  PICKUP_CREATE_ADD_BOX: 'PICKUP_CREATE_ADD_BOX',
  PICKUP_CREATE_DELETE_BOX: 'PICKUP_CREATE_DELETE_BOX',
  PICKUP_EDIT_SET_DATA: 'PICKUP_EDIT_SET_DATA',
  PICKUP_EDIT_SET_TYPE: 'PICKUP_EDIT_SET_TYPE',
};
