export default {
  USERS_SET_DATA: 'USERS_SET_DATA',
  USERS_ADD_ACTION: 'USERS_ADD_ACTION',
  USERS_ADD_ACTION_SUCCESS: 'USERS_ADD_ACTION_SUCCESS',
  USERS_ADD_ACTION_ERROR: 'USERS_ADD_ACTION_ERROR',
};
