export const TABLE_SET_BOXES_DATA = 'EXPRESS_TABLE_SET_BOXESDATA';
export const TABLE_SET_BOXES_TOTAL = 'EXPRESS_TABLE_SET_BOXES_TOTAL';
export const TABLE_BOXES_SET_STATUSES = 'EXPRESS_TABLE_BOXES_SET_STATUSES';
export const TABLE_BOXES_SET_LOADING = 'EXPRESS_TABLE_BOXES_SET_LOADING';
export const TABLE_BOXES_SET_ERROR = 'EXPRESS_TABLE_BOXES_SET_ERROR';
export const TABLE_BOXES_FETCH_DATA = 'EXPRESS_TABLE_BOXES_FETCH_DATA';
export const TABLE_BOXES_FETCH_STATUSES = 'EXPRESS_TABLE_BOXES_FETCH_STATUSES';
