export const TABLE_FEDEX_HEADER_SET = 'EXPRESS_TABLE_FEDEX_HEADER_SET';
export const TABLE_FEDEX_HEADER_UPDATE = 'EXPRESS_TABLE_FEDEX_HEADER_UPDATE';
export const TABLE_FEDEX_HEADER_SAVE = 'EXPRESS_TABLE_FEDEX_HEADER_SAVE';
export const TABLE_FEDEX_HEADER_RESET = 'EXPRESS_TABLE_FEDEX_HEADER_RESET';
