export const TABLE_ORDERS_HEADER_SET = 'EXPRESS_TABLE_ORDERS_HEADER_SET';
export const TABLE_ORDERS_HEADER_UPDATE = 'EXPRESS_TABLE_ORDERS_HEADER_UPDATE';
export const TABLE_ORDERS_HEADER_SAVE = 'EXPRESS_TABLE_ORDERS_HEADER_SAVE';
export const TABLE_ORDERS_HEADER_RESET = 'EXPRESS_TABLE_ORDERS_HEADER_RESET';
export const TABLE_ORDERS_SAGA_ONSEARCH_ACTION =
  'EXPRESS_TABLE_ORDERS_SAGA_ONSEARCH_ACTION';
export const TABLE_ORDERS_SET_LOADING = 'EXPRESS_TABLE_ORDERS_SET_LOADING';
export const TABLE_ORDERS_SET_DATA = 'EXPRESS_TABLE_ORDERS_SET_DATA';
export const TABLE_ORDERS_SET_TOTAL = 'EXPRESS_TABLE_ORDERS_SET_TOTAL';
export const TABLE_ORDERS_FETCH_DATA = 'EXPRESS_TABLE_ORDERS_FETCH_DATA';
export const TABLE_ORDERS_ERROR = 'EXPRESS_TABLE_ORDERS_ERROR';
export const TABLE_ORDERS_FETCH_STATUSES =
  'EXPRESS_TABLE_ORDERS_FETCH_STATUSES';
export const TABLE_ORDERS_SET_STATUSES = 'EXPRESS_TABLE_ORDERS_SET_STATUSES';
export const TABLE_ORDERS_FETCH_PAYMENT_STATUSES =
  'EXPRESS_TABLE_ORDERS_FETCH_PAYMENT_STATUSES';
export const TABLE_ORDERS_SET_PAYMENT_STATUSES =
  'EXPRESS_TABLE_ORDERS_SET_PAYMENT_STATUSES';
