export const TABLE_SHIPMENTS_HEADER_SET = 'EXPRESS_TABLE_SHIPMENTS_HEADER_SET';
export const TABLE_SHIPMENTS_HEADER_UPDATE = 'EXPRESS_TABLE_SHIPMENTS_HEADER_UPDATE';
export const TABLE_SHIPMENTS_HEADER_SAVE = 'EXPRESS_TABLE_SHIPMENTS_HEADER_SAVE';
export const TABLE_SHIPMENTS_HEADER_RESET = 'EXPRESS_TABLE_SHIPMENTS_HEADER_RESET';
export const TABLE_SHIPMENT_SINGLE_VIEW_HEADER_SET = 'TABLE_SHIPMENT_SINGLE_VIEW_HEADER_SET';
export const TABLE_SHIPMENT_SINGLE_VIEW_HEADER_UPDATE = 'TABLE_SHIPMENT_SINGLE_VIEW_HEADER_UPDATE';
export const TABLE_SHIPMENT_SINGLE_VIEW_HEADER_SAVE = 'TABLE_SHIPMENT_SINGLE_VIEW_HEADER_SAVE';
export const TABLE_SHIPMENT_SINGLE_VIEW_HEADER_RESET = 'TABLE_SHIPMENT_SINGLE_VIEW_HEADER_RESET';
export const TABLE_SHIPMENTS_SET_LOADING = 'EXPRESS_TABLE_SHIPMENTS_SET_LOADING';
export const TABLE_SHIPMENTS_SET_DATA = 'EXPRESS_TABLE_SHIPMENTS_SET_DATA';
export const TABLE_SHIPMENTS_SET_BOXESDATA = 'EXPRESS_TABLE_SHIPMENTS_SET_BOXESDATA';
export const TABLE_SHIPMENTS_SET_TOTAL = 'EXPRESS_TABLE_SHIPMENTS_SET_TOTAL';
export const TABLE_SHIPMENTS_SET_BOXES_TOTAL = 'EXPRESS_TABLE_SHIPMENTS_SET_BOXES_TOTAL';
export const TABLE_SHIPMENTS_FETCH_DATA = 'EXPRESS_TABLE_SHIPMENTS_FETCH_DATA';
export const TABLE_SHIPMENTS_SINGLE_FETCH_BOXES = 'TABLE_SHIPMENTS_SINGLE_FETCH_BOXES';
export const TABLE_SHIPMENTS_FETCH_STATUSES = 'EXPRESS_TABLE_SHIPMENTS_FETCH_STATUSES';
export const TABLE_SHIPMENTS_FETCH_PAYMENT_STATUSES = 'EXPRESS_TABLE_SHIPMENTS_FETCH_PAYMENT_STATUSES';
export const TABLE_SHIPMENTS_ERROR = 'EXPRESS_TABLE_SHIPMENTS_ERROR';
export const TABLE_SHIPMENTS_SET_STATUSES = 'EXPRESS_TABLE_SHIPMENTS_SET_STATUSES';
export const TABLE_SHIPMENTS_SET_PAYMENT_STATUSES = 'EXPRESS_TABLE_SHIPMENTS_SET_PAYMENT_STATUSES';

// Shipment boxes
export const SHIPMENT_CREATE_NAME = 'EXPRESS_TABLE_SHIPMENT_CREATE_NAME';
export const TABLE_SHIPMENTS_BOXES_SET_STATUSES = 'EXPRESS_TABLE_SHIPMENTS_BOXES_SET_STATUSES';
