export const TABLE_SPENDINGS_HEADER_SET = 'EXPRESS_TABLE_SPENDINGS_HEADER_SET';
export const TABLE_SPENDINGS_HEADER_UPDATE =
  'EXPRESS_TABLE_SPENDINGS_HEADER_UPDATE';
export const TABLE_SPENDINGS_HEADER_SAVE =
  'EXPRESS_TABLE_SPENDINGS_HEADER_SAVE';
export const TABLE_SPENDINGS_HEADER_RESET =
  'EXPRESS_TABLE_SPENDINGS_HEADER_RESET';
export const TABLE_SPENDINGS_SET_LOADING =
  'EXPRESS_TABLE_SPENDINGS_SET_LOADING';
export const TABLE_SPENDINGS_SET_DATA = 'EXPRESS_TABLE_SPENDINGS_SET_DATA';
export const TABLE_SPENDINGS_SET_TOTAL = 'EXPRESS_TABLE_SPENDINGS_SET_TOTAL';
export const TABLE_SPENDINGS_FETCH_DATA = 'EXPRESS_TABLE_SPENDINGS_FETCH_DATA';
export const TABLE_SPENDINGS_ERROR = 'EXPRESS_TABLE_SPENDINGS_ERROR';
